---
title: "Network Segregation and Homophily"
author: "Michał Bojanowski"
date: "July 7, 2020"
output: 
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{Network Segregation and Homophily}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(netseg)
library(igraph)

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svg",
  out.width = "100%",
  fig.width=10,
  fig.height=6
)

set.seed(666)
```


# Data

Here is the data

```{r load-data}
data(Classroom)
```

```{r plot-data}
plot(
  Classroom,
  layout = graphlayouts::layout_with_stress,
  vertex.color = c("Skyblue", "Pink")[match(V(Classroom)$gender, c("Boy", "Girl"))],
  vertex.label = NA,
  vertex.size = 10,
  edge.arrow.size = .7
)
legend(
  "topright",
  pch = 21,
  legend = c("Boy", "Girl"),
  pt.bg = c("Skyblue", "Pink"),
  pt.cex = 2,
  bty = "n"
)
```



# Directed networks


# Undirected networks
